<?php
/**
 * Author: samokspv <samokspv@yandex.ru>
 * Date: 29.10.2014
 * Time: 15:00:00
 */

$pluginPath = App::pluginPath('ExcludeSimilarDocs');
$defaultConfig = array(
	'types' => array(
		'simple' => array(
			'fields' => array(
				'title',
				'description'
			)
		),
		'shingles' => array(
			'fields' => array(
				'title',
				'description'
			),
			'length' => 10,
			'allowSimilarity' => 1,
			'stopWords' => array(
				// prepositions and conjunction
				'aboard',
				'about',
				'above',
				'absent',
				'across',
				'afore',
				'after',
				'against',
				'along',
				'amid',
				'amidst',
				'among',
				'amongst',
				'around',
				'as',
				'aside',
				'aslant',
				'astride',
				'at',
				'athwart',
				'atop',
				'bar',
				'before',
				'behind',
				'below',
				'beneath',
				'beside',
				'besides',
				'between',
				'betwixt',
				'beyond',
				'but',
				'by',
				'circa',
				'despite',
				'down',
				'except',
				'for',
				'from',
				'given',
				'in',
				'inside',
				'into',
				'like',
				'mid',
				'minus',
				'near',
				'neath',
				'next',
				'notwithstanding',
				'of',
				'off',
				'on',
				'opposite',
				'out',
				'outside',
				'over',
				'pace',
				'per',
				'plus',
				'post',
				'pro',
				'qua',
				'round',
				'save',
				'since',
				'than',
				'through',
				'till',
				'times',
				'to',
				'toward',
				'towards',
				'under',
				'underneath',
				'unlike',
				'until',
				'up',
				'versus',
				'via',
				'vice',
				'with',
				'without',
				'barring',
				'concerning',
				'considering',
				'depending',
				'during',
				'granted',
				'excepting',
				'excluding',
				'failing',
				'following',
				'including',
				'past',
				'pending',
				'regarding',
				'alongside',
				'within',
				'outside',
				'upon',
				'onto',
				'throughout',
				'wherewith',
				'according to',
				'ahead of',
				'apart from',
				'as far as',
				'as for',
				'as of',
				'as per',
				'as regards',
				'aside from',
				'as well as',
				'away from',
				'because of',
				'by force of',
				'by means of',
				'by virtue of',
				'close to',
				'contrary to',
				'due to',
				'except for',
				'far from',
				'for the sake of',
				'in accordance with',
				'in addition to',
				'in case of',
				'in connection with',
				'in consequence of',
				'in front of',
				'in spite of',
				'in the back of',
				'in the course of',
				'in the event of',
				'in the middle of',
				'in to',
				'into',
				'inside of',
				'instead of',
				'in view of',
				'near to',
				'next to',
				'on account of',
				'on to',
				'onto',
				'on top of',
				'opposite to',
				'out of',
				'outside of',
				'owing to',
				'thanks to',
				'up to',
				'with regard to',
				'with respect to'
			),
			'stopSymbols' => array(
				"'", ',', '.', '/', '«', '»', '#', ';', 
				':', '@', '~', '[', ']', '{', '}', '=', 
				'-', '+', ')', '(', '*', '&', '^', '%', 
				'$', '<', '>', '?', '!', '"', "\t", "\n", "\r",
				'…'
			)
		)
	)
);